spring.application.name=backend
# Configuración del servidor
server.port=8080

# Conexión a la base de datos de Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/wau_db
spring.datasource.username=postgres
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (creará y actualizará las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true